Repository codeforanchorage/land_acknowledgement, pull requests merged in 2020-08, with the labels that each got.

#10 Responde with multiple territories. Add basic tests
  src/app/db.py
  src/app/web.py
  src/requirements.txt
  src/tests/test_api.py
  src/tests/test_integration.py
Labels: enhancement

#13 Add Land Acknowledgement splash page
  docs/CNAME
  docs/css/style.css
  docs/img/alaskaPhoto.jpg
  docs/img/coldCar.svg
  docs/index.html
Labels: documentation, enhancement

#16 Final Website Deployment
  docs/CNAME
  docs/css/style.css
  docs/img/alaskaPhoto.jpg
  docs/index.html
Labels: documentation, enhancement

#17 Add MIT LICENSE
  LICENSE
Labels: documentation

#20 Tweak front-end assets
  docs/css/style.css
  docs/index.html
Labels: enhancement
